const ErrorConstants = {
  NAME_ERROR: 'Please enter name',
  FIRST_NAME_ERROR: 'Please enter first name',
  MINIMUM_FIRST_NAME_ERROR: 'Firstname must be at least 3 characters long',
  MAXIMUM_FIRST_NAME_ERROR: 'Fisrtname must be less than 50 characters',
  LAST_NAME_ERROR: 'Please enter last name',
  MINIMUM_LAST_NAME_ERROR: 'Lastname must be at least 3 characters long',
  MAXIMUM_LAST_NAME_ERROR: 'Lastname must be less than 50 characters',
  ADDRESS_ERROR: 'Please enter address',
  EMAIL_ERROR: 'Please enter email',
  VALID_EMAIL_ERROR: 'Please enter valid email',
  OLD_PASSWORD: 'please enter your old password',
  PASSWORD_ERROR: 'Please enter password',
  MINIMUM_PASSWORD_ERROR: 'Password must be at least 8 characters long',
  LOWERCASE_ERROR: 'Password must include at least one lowercase letter.',
  UPPERCASE_ERROR: 'Password must include at least one uppercase letter.',
  DIGIT_ERROR: 'Password must include at least one digit.',
  SPECIAL_CHAR_ERROR: 'Password must include at least one special character.',
  MATCH_PASSWORD_ERROR: 'Passwords must match',
  STRONG_PASSWORD_ERROR: 'Password must contain 8 characters, 1 uppercase, 1 lowercase, 1 number and 1 special case character',
  MOBILE_NO_ERROR: 'Please enter mobile no',
  PHONE_NO_ERROR: 'Please enter phone number',
  DESCRIPTION_ERROR: 'Please enter description',
  TITLE_ERROR: 'Please enter title',
  IMAGE_ERROR: 'Please upload image',
  TYPE_ERROR: 'Please select type',
  RESTAURANT_NAME_ERROR: 'Please enter restaurant name',
  MINIMUM_RESTAURANT_NAME_ERROR: 'Restaurant name must be atleast 2 character long',
  MAXIMUM_RESTAURANT_NAME_ERROR: 'Restaurant name must be less than 50 characters',
  COMPANY_NAME_ERROR: 'Please enter company name',
  CARD_HOLDER_ERROR: 'Please enter card holder name',
  CARD_NO_ERROR: 'Please enter card no',
  CVV_ERROR: 'Please enter cvv code',
  EXPIRY_DATE_ERROR: 'Please enter expiry date',
  ZIPCODE_ERROR: 'Please enter zipcode',
  STREET_NAME_ERROR: 'Please enter street name',
  CITY_NAME_ERROR: 'Please enter city name',
  COUNTRY_ERROR: 'Please select country',
  STATE_ERROR: 'Please select state',
  TIMEZONE_ERROR: 'Please select timezone',
  SUBJECT_ERROR: 'Please enter subject',
  MESSAGE_ERROR: 'Please enter message',
  HEADLINE_ERROR: 'Please enter headline',
  DISCOUNT_ERROR: 'Please enter discount',
  EMAIL_SUBJECT_ERROR: 'Please enter email subject',
  TEXT_ERROR: 'Please enter text',
  PROMOTION_ERROR: 'Please enter promotion',
  SELECT_CATEGORY_ERROR: 'Please select category',
  PRICE_ERROR: 'Please enter price',
  MINIMUM_ERROR: 'Please enter minimum value',
  MAXIMUM_ERROR: 'Please enter maximum value',
  SELECT_ADDON_ERROR: 'Please enter maximum value',
  SERVICE_CHARGE_ERROR: 'Please enter service charge',
  URL_ERROR: 'Please enter URL',
  VALID_URL_ERROR: 'Please enter valid URL',
  AMOUNT_ERROR: 'Please enter amount',
  FROM_VALUE_ERROR: 'Please enter from value',
  TO_VALUE_ERROR: 'Please enter to value',
  INSTRUNCTION_ERROR: 'Please enter instrunction',
  COLOR_ERROR: 'Please select color',
  MIN_TIME_ERROR: 'Please enter minimum time',
  MAX_TIME_ERROR: 'Please enter maximum time',
  TAX_NAME_ERROR: 'Please enter tax name',
  SALES_TAX_ERROR: 'Please enter sales tax',
  CURRENCY_ERROR: 'Please enter currency',
  DELIVERY_FEE_ERROR: 'Please enter delivery fee',
  LINK_ERROR: 'Please enter {name} link',
  TAX_CATEGORY_ERROR: 'Please enter taxe category name',
  MIN_CHAR_ERROR: 'Maximum {value} characters are allowed',
  MINIMUM_ITEMS_ERROR: 'At least one item must be selected',
  COUPON_ERROR: 'Please enter coupon code',
  STOCK_ERROR: 'Please enter stock limit',
  DATE_ERROR: 'Please select {name} date',
  PREFIX_ERROR: 'Please enter prefix',
}

export default ErrorConstants
