const Constants = {
  PASSWORD_REGEX: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,}$/,
  EMAIL_REGEX: /^[a-z0-9][a-z0-9-_\.]+@([a-z]|[a-z0-9]?[a-z0-9-]+[a-z0-9])\.[a-z0-9]{2,10}(?:\.[a-z]{2,10})?$/i,
  NAME_REGEX: /^[a-zA-Z]+[ ]{0,1}[a-zA-Z ]*$/,
  ALPHABET_REGEX: /[^ a-zA-Z]/g,
  NUMBER_REGEX: /^(?!(0))[0-9]+$/, // ensures that the number does not start with 0
  DESC_REGEX: /[^ a-zA-Z0-9!@#$%^&*()_+{}]/g,
  SPACE_REGEX: /^\s/,
  REMOVE_SPACE_REGEX: /&nbsp;/g,
  PASSOWORD_MATCH_REGEX: /[^a-zA-Z0-9@!#$&*>]/g,
  IS_IMAGE_REGEX: /\.(jpg|jpeg|png|webp|avif|gif|svg)$/,
  IS_VIDEO_REGEX: /\.(mp4|avi|mov|mkv|webm)$/,
  STRING_REGEX: /[^ a-zA-Z0-9]/g,
  DISCOUNT_REGEX: /^(?!00)(\d{0,2}(\.(?!00)\d{0,2})?)?$/,
  NO_REGEX: /[^0-9]/g, // used to find and remove non-numeric characters from a string
  MOBILE_NO_REGEX: /^(?!0+$)[0-9\(\)-]{10,}$/,
  URL_REGEX: /^(ftp|http|https):\/\/[^ "]+$/,
  LOCAL_STORAGE_PREFIX: '1ROOS',
  LOCAL_STORAGE_KEY: '1ROOS$Tjcg@2024',
  VERSION_KEY: 'version',
  CONFIG_DATA: 'configdata',
  TOKEN_EXPIRY_TIME: 'tokenexpirytime',
  USER_TOKEN: 'uToken',
  REFRESH_TOKEN: 'refreshToken',
  ALL_TOKEN_TIME: 'alltokentime',
  LOGGED_IN: 'logged_in',
  PERMISSIONS: 'permissions',
  UCID: 'ucid',
  RID: 'rid',
  REMEMBER_ME: 'remember_me',
  IMAGE_SIZE: 3145728,
  IMAGE_TYPE: { 'image/*': ['.png', '.jpg', '.jpeg', '.webp'] },
  CSV_TYPE: { 'text/csv': ['.csv'] },
  PDF_SIZE: 10485760,
  PDF_TYPE: { 'application/pdf': ['.pdf'] },
  ENCRYPT_KEY: 'd1e8a70b5ccab1dc2f56bbf7e99f064a660c08e361a35751b9c483c88943d082',
  ALGORITHM: 'aes-256-ctr',
}

export default Constants
